import os
import pandas as pd
import plotly.express as px
import plotly.io as pio
from langchain_core.tools import tool

import json

@tool
def build_interactive_dashboard(
    data_path: str,
    title: str,
    charts_config_json: str
) -> str:
    """
    Builds a professional, Glassmorphism-styled HTML dashboard with multiple interactive charts.
    """
    try:
        charts_config = json.loads(charts_config_json)
        if not os.path.exists(data_path):
            # Try to find it in the data folder if relative path fails
            alt_path = os.path.join("data", os.path.basename(data_path))
            if os.path.exists(alt_path):
                data_path = alt_path
            else:
                return f"Error: Data file {data_path} not found."
            
        df = pd.read_csv(data_path)
        
        # ── INTERACTIVE COMPONENTS ──────────────────────────────────────────
        html_charts = []
        for config in charts_config:
            ctype = config.get("type", "line").lower()
            x = config.get("x")
            y = config.get("y")
            ctitle = config.get("title", f"{ctype.capitalize()} Analysis")
            
            if ctype == "line":
                fig = px.line(df, x=x, y=y, title=ctitle, template="plotly_dark", color_discrete_sequence=["#00d4aa"])
            elif ctype == "bar":
                fig = px.bar(df, x=x, y=y, title=ctitle, template="plotly_dark", color_discrete_sequence=["#3b82f6"])
            elif ctype == "scatter":
                fig = px.scatter(df, x=x, y=y, title=ctitle, template="plotly_dark", color_discrete_sequence=["#ec4899"])
            elif ctype == "pie":
                fig = px.pie(df, names=x, values=y, title=ctitle, template="plotly_dark")
            else:
                fig = px.histogram(df, x=x or y, title=ctitle, template="plotly_dark")
                
            fig.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", 
                plot_bgcolor="rgba(0,0,0,0)",
                font={"family": "Inter, sans-serif"},
                margin=dict(l=20, r=20, t=50, b=20)
            )
            html_charts.append(pio.to_html(fig, full_html=False, include_plotlyjs='cdn'))
            
        # ── GLASSMORPHISM TEMPLATE ─────────────────────────────────────────
        full_html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title} | InsightForge AI</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg: #030712;
            --glass: rgba(17, 24, 39, 0.7);
            --border: rgba(255, 255, 255, 0.1);
            --accent: #00d4aa;
        }}
        body {{
            background: radial-gradient(circle at top right, #0d1420, var(--bg));
            color: #f8fafc;
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 40px;
            min-height: 100vh;
        }}
        .header {{
            text-align: center;
            margin-bottom: 50px;
        }}
        h1 {{
            font-size: 3rem;
            font-weight: 700;
            background: linear-gradient(to right, #00d4aa, #3b82f6);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin: 0;
        }}
        .dashboard-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 30px;
        }}
        .chart-card {{
            background: var(--glass);
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border: 1px solid var(--border);
            border-radius: 20px;
            padding: 20px;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
            transition: transform 0.3s ease, border-color 0.3s ease;
        }}
        .chart-card:hover {{
            transform: translateY(-5px);
            border-color: var(--accent);
        }}
        .footer {{
            text-align: center;
            margin-top: 60px;
            font-size: 0.9rem;
            color: #64748b;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p style="color: #64748b;">Autonomous Insight Generated by InsightForge AI</p>
    </div>
    
    <div class="dashboard-grid">
        {"".join([f'<div class="chart-card">{chart}</div>' for chart in html_charts])}
    </div>

    <div class="footer">
        &copy; 2026 InsightForge AI · Advanced Analytical Agent Team · {df.shape[0]} rows analyzed
    </div>
</body>
</html>
        """
        
        dir_path = "output_graphs/dashboards"
        os.makedirs(dir_path, exist_ok=True)
        safe_title = title.lower().replace(' ', '_').replace('/', '_')
        filename = f"{safe_title}.html"
        save_path = os.path.join(dir_path, filename)
        
        with open(save_path, "w", encoding="utf-8") as f:
            f.write(full_html)
            
        return f"Premium Glassmorphism Dashboard '{title}' established.\n[[DASHBOARD:{filename}]]"
        
    except Exception as e:
        return f"Dashboard builder error: {str(e)}"
        
    except Exception as e:
        return f"Dashboard builder error: {str(e)}"
