from langchain_core.tools import tool
import os
from datetime import datetime

# Directory where PPTXs will be saved
REPORTS_DIR = os.path.join("output_graphs", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

# Store the last generated pptx path so the download endpoint can serve it
_last_pptx_path = {"path": None}


def get_last_pptx_path() -> str | None:
    return _last_pptx_path["path"]


@tool
def export_presentation_deck(title: str, slides_json: str, filename: str = "") -> str:
    """
    Exports a professional PowerPoint (.pptx) presentation deck.
    Call this when the user wants a slide deck, PowerPoint, or presentation summary.
    
    Args:
        title: The presentation title for the cover slide.
        slides_json: A JSON string representing a list of slides.
                     Format: [{"title": "Slide Title", "content": "Bullet points or text", "image_path": "optional.png"}]
        filename: Optional custom filename (without extension).
    
    Returns a confirmation string with the saved file path and download hint.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.enum.text import PP_ALIGN
        import json
    except ImportError:
        return "Error: 'python-pptx' is not installed. Run: pip install python-pptx"

    try:
        slides_data = json.loads(slides_json)
    except Exception as e:
        return f"Error parsing slides_json: {str(e)}. Ensure it is a valid JSON list of slide objects."

    try:
        # ── File path ────────────────────────────────────────────────────────
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = (filename or title).replace(" ", "_").replace("/", "-")[:40]
        pptx_filename = f"{safe_name}_{timestamp}.pptx"
        pptx_path = os.path.join(REPORTS_DIR, pptx_filename)

        # ── Build presentation ──────────────────────────────────────────────
        prs = Presentation()

        # 1. Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]

        title_shape.text = title
        subtitle_shape.text = f"Generated by InsightForge AI\n{datetime.now().strftime('%B %d, %Y')}"

        # 2. Content Slides
        for slide_data in slides_data:
            s_title = slide_data.get("title", "Untitled Slide")
            s_content = slide_data.get("content", "")
            s_image = slide_data.get("image_path", None)

            # Use layout 1 (Title and Content) or 5 (Title Only if image is primary)
            if s_image and not s_content:
                slide_layout = prs.slide_layouts[5] # Title Only
            else:
                slide_layout = prs.slide_layouts[1] # Title and Content
            
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = s_title

            if s_content:
                tf = slide.placeholders[1].text_frame
                tf.text = s_content
                # Basic formatting for the text frame could be added here if needed

            if s_image:
                # Resolve path - check if it's in output_graphs
                img_path = s_image
                if not os.path.exists(img_path):
                    # Try looking in standard output directories
                    alt_path = os.path.join("output_graphs", s_image)
                    if os.path.exists(alt_path):
                        img_path = alt_path
                
                if os.path.exists(img_path):
                    # Position image on the right if there's text, or center if not
                    if s_content:
                        # Add image on the right side
                        left = Inches(6)
                        top = Inches(1.5)
                        width = Inches(3.5)
                        slide.shapes.add_picture(img_path, left, top, width=width)
                    else:
                        # Center large image
                        left = Inches(1)
                        top = Inches(1.5)
                        width = Inches(8)
                        slide.shapes.add_picture(img_path, left, top, width=width)

        # ── Save ─────────────────────────────────────────────────────────────
        prs.save(pptx_path)
        _last_pptx_path["path"] = pptx_path

        return (
            f"✅ PowerPoint presentation exported successfully!\n"
            f"**File:** {pptx_filename}\n"
            f"**Slides:** {len(slides_data) + 1}\n\n"
            f"🔗 **Download:** Navigate to `/api/export-pptx` in your browser.\n"
            f"[[PRESENTATION:{pptx_filename}]]"
        )

    except Exception as e:
        return f"Error generating PowerPoint: {str(e)}"
